{% set name = "keyrings.alt" %}
{% set version = "3.5.1" %}
{% set sha256 = "22bf99f80de1b0586af7c1a181fc32264447251cec6af164e33e1e24d2981127" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
  run:
    - keyring
    - python

test:
  imports:
    - keyrings.alt

about:
  home: https://github.com/jaraco/keyrings.alt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Alternate keyring backend implementations for use with the keyring package.

  doc_url: http://pythonhosted.org/keyrings.alt/
  dev_url: https://github.com/jaraco/keyrings.alt/

extra:
  recipe-maintainers:
    - astaric
    - yarikoptic
