{% set name = "keyrings.alt" %}
{% set version = "3.1" %}
{% set sha256 = "b59c86b67b9027a86e841a49efc41025bcc3b1b0308629617b66b7011e52db5a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
  run:
    - keyring
    - python

test:
  imports:
    - keyrings.alt

about:
  home: https://github.com/jaraco/keyrings.alt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Alternate keyring backend implementations for use with the keyring package.'

  doc_url: http://pythonhosted.org/keyrings.alt/
  dev_url: https://github.com/jaraco/keyrings.alt/

extra:
  recipe-maintainers:
    - astaric
