{% set name = "keyrings.alt" %}
{% set version = "2.3" %}
{% set sha256 = "5cb9b6cdb5ce5e8216533e342d3e1b418ddd210466834061966d7dc1a4736f2d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm >=1.15.0
  run:
    - keyring
    - six
    - python

test:
  imports:
    - keyrings.alt

about:
  home: https://github.com/jaraco/keyrings.alt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Alternate keyring backend implementations for use with the keyring package.'

  doc_url: http://pythonhosted.org/keyrings.alt/
  dev_url: https://github.com/jaraco/keyrings.alt/

extra:
  recipe-maintainers:
    - astaric
